name: cutout
description: "Flutter package for CutOut image segmentation implementation that enables the utilization of C++ code for image processing."
version: 25.1.0
homepage: https://github.com/grandeclip/cutout_flutter

environment:
  sdk: ^3.5.3
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  ffi: ^2.1.3
  onnxruntime: ^1.4.1  # means that original onnxruntime == 1.15.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: com.grandeclip.cutout
        pluginClass: CutoutPlugin
      ios:
        pluginClass: CutoutPlugin
